### ISSUE TITLE
Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com fal-1a.prd.ece.vwg-connect.com:443

### ISSUE THREAD

**Issue by TobiasSt78** [TA2k/ioBroker.vw-connect#18]
Hallo,

heute installiert und npb build usw. probiert.

Personal Data werden aktualisiert, Fahrzeugdaten nicht.
Ich habe VW We Connect und die App funktioniert auch.

Log:
vw-connect.0 | 2020-06-14 18:44:18.564 | error | (10402) status update Failed
-- | -- | -- | --
vw-connect.0 | 2020-06-14 18:44:18.563 | error | (10402) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com fal-1a.prd.ece.vwg-connect.com:443
vw-connect.0 | 2020-06-14 18:44:18.556 | error | (10402) get vehicle data Failed
vw-connect.0 | 2020-06-14 18:44:18.513 | error | (10402) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com fal-1a.prd.ece.vwg-connect.com:443
vw-connect.0 | 2020-06-14 18:44:18.488 | debug | (10402) Set URL to: https://fal-1a.prd.ece.vwg-connect.com
vw-connect.0 | 2020-06-14 18:44:18.488 | debug | (10402) [object Object]
vw-connect.0 | 2020-06-14 18:44:16.620 | error | (10402) status update Failed
vw-connect.0 | 2020-06-14 18:44:16.619 | error | (10402) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com fal-1a.prd.ece.vwg-connect.com:443
vw-connect.0 | 2020-06-14 18:44:16.616 | error | (10402) get vehicle data Failed
vw-connect.0 | 2020-06-14 18:44:16.615 | error | (10402) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com fal-1a.prd.ece.vwg-connect.com:443
vw-connect.0 | 2020-06-14 18:44:16.595 | debug | (10402) Set URL to: https://fal-1a.prd.ece.vwg-connect.com
vw-connect.0 | 2020-06-14 18:44:16.595 | debug | (10402) [object Object]
vw-connect.0 | 2020-06-14 18:44:16.264 | debug | (10402) getHomeRegion
vw-connect.0 | 2020-06-14 18:44:16.262 | debug | (10402) getHomeRegion
...

Würde mich sehr freuen, wenn der Adapter laufen würde.

Gruß, Tobias.

**Comment by TA2k** [comment]
Ist das Problem immernoch vorhanden? Wenn ja im Forum über Privatnachricht melden.

**Comment by sky-it** [comment]
Habe den Adapter gestern installiert und bekomme leider auch die Meldungen:

vw-connect.0 | 2020-06-17 09:42:30.491 | error | (13436) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com
-- | -- | -- | --

Ansonsten funktioniert der Adapter, hab jetzt aber auch keine Fahrzeuge die "ferngesteuert" werden können

**Comment by TA2k** [comment]
Can you try to install via github?

**Comment by sky-it** [comment]
Gerade frisch von GitHub installiert und anschließend gestartet:


vw-connect.0 | 2020-06-17 13:00:20.976 | error | (12449) status update Failed
-- | -- | -- | --
vw-connect.0 | 2020-06-17 13:00:20.974 | error | (12449) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com
vw-connect.0 | 2020-06-17 13:00:20.910 | error | (12449) status update Failed
vw-connect.0 | 2020-06-17 13:00:20.909 | error | (12449) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com
vw-connect.0 | 2020-06-17 13:00:19.059 | error | (12449) status update Failed
vw-connect.0 | 2020-06-17 13:00:19.057 | error | (12449) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com
vw-connect.0 | 2020-06-17 13:00:14.849 | info | (12449) starting. Version 0.0.16 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v12.18.0, js-controller: 3.1.5

**Comment by sky-it** [comment]
So:
- Adapter gelöscht
- Adapter über Git neu installiert
- Instanz hinzugefügt
Fehler:

vw-connect.0 | 2020-06-17 13:16:16.656 | error | (18633) status update Failed
-- | -- | -- | --
vw-connect.0 | 2020-06-17 13:16:16.654 | error | (18633) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com
vw-connect.0 | 2020-06-17 13:16:16.649 | error | (18633) status update Failed
vw-connect.0 | 2020-06-17 13:16:16.647 | error | (18633) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com
vw-connect.0 | 2020-06-17 13:16:14.571 | error | (18633) status update Failed
vw-connect.0 | 2020-06-17 13:16:14.569 | error | (18633) Error: getaddrinfo ENOTFOUND fal-1a.prd.ece.vwg-connect.com
vw-connect.0 | 2020-06-17 13:16:11.541 | info | (18633) starting. Version 0.0.16 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v12.18.0, js-controller: 3.1.5
vw-connect.0 | 2020-06-17 13:16:11.516 | info | (18633) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

**Comment by TA2k** [comment]
Kann mir tombox jemand im forum via privatnachricht zugangsdaten zusenden damit ich es lösen kann.
