### ISSUE TITLE
Axios Error 404 | get id status Failed

### ISSUE THREAD

**Issue by GoClyde** [TA2k/ioBroker.vw-connect#219]
Ich bekomme seit heute Vormittag keinen aktuellen Status mehr. Im Protokoll stehen nach jeder versuchten Abfrage folgende drei Errors:
'<html><body>

Quelle | Zeit | - | Nachricht
-- | -- | -- | --
vw-connect.0 | 2022-12-05 16:17:31.088 | error | get id status Failed
vw-connect.0 | 2022-12-05 16:17:31.087 | error | {"message":"Not Found"}
vw-connect.0 | 2022-12-05 16:17:31.086 | error | AxiosError: Request failed with status code 404

</body>
</html>'

Sowohl Version 0.0.52 als auch 53 betroffen
VW ID.4

**Comment by ClarreJu** [comment]
I get the same error... Someting temporarly broken at VW or have they changes something?
I believe I get some strange value at the first stage of the authentification. I have implemented this in JavaScript (google script) so my code looks a bit different.

Anyone smarter than me that can find out what has changed?

**Comment by TA2k** [comment]
fixed with v0.0.55 GitHub or npm

**Comment by ClarreJu** [comment]
Thank you! Could you hint what's changed? Since I have implemented your beautiful code in JavaScript... Would be very appreciated! If not, no worries and thanks any way!

All the best

C-H

**Comment by TA2k** [comment]
The javascript code adopting the structure of the VAG Apps.
Its a mess..

The request url for status is changed
https://github.com/TA2k/ioBroker.vw-connect/commit/573e32e82d84b99fbe71cfcb8be7770990345d8d

**Comment by ClarreJu** [comment]
Thank you very much!

All the best

C-H

Claes-Henrik Julander
+46 70 7467535

Den mån 5 dec. 2022 22:22TA2k ***@***.***> skrev:

**Comment by GoClyde** [comment]
> fixed with v0.0.55 GitHub or npm

did not do that before. How can I update my version now?

**Comment by TA2k** [comment]
should now be available as normal update

**Comment by ClarreJu** [comment]
Hi again!

Since the last couple of weeks I have completely lost it again... As you might remember I am tracing your code in Google script in the cloud. I have an id.3.
Roughly two weeks ago they change the adress for logging in. I nicked that from your code and all worked fine. Since about a week I had to log in again on the app and since then I don't get the code to work. I guess it has to do with the VWv2? But I having problem following the changes in your code. I have read it for hours so that I almost know it by heart! :-) . It seams to me that there must be some things changed with the cookies and/or headers in the second request? 
If you could point me in the direction of whats new, I would really appreciate it! If you don't have the time, or feel like it, I fully understand! 

Sorry for beeing a pain.

All the best

C-H

**Comment by TA2k** [comment]
id has server name change in recent past

**Comment by ClarreJu** [comment]
Only that? I changed that a couple of weeks ago. Does the VWv2 not affect
Id?

Then I must have messed up something else...

Thank you!

All the best

C-H


*Claes-Henrik Julander*

Svipdag AB

Danderydsgatan 15, S-114 26 Stockholm, Sverige
Mobil: +46 (70) 7467535


Den sön 19 mars 2023 kl 14:55 skrev TA2k ***@***.***>:
